# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: units.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bunits.proto*\xd4\x02\n\x05Units\x12\x14\n\x10UNIT_UNSPECIFIED\x10\x00\x12\x07\n\x03KPH\x10\x01\x12\x07\n\x03MPS\x10\x02\x12\x0b\n\x07\x43\x45LSIUS\x10\x03\x12\r\n\tFAHREHEIT\x10\x04\x12\x08\n\x04MBAR\x10\x05\x12\x06\n\x02PA\x10\x06\x12\x0b\n\x07PERCENT\x10\x07\x12\n\n\x06Lumens\x10\x08\x12\x06\n\x02KM\x10\t\x12\x06\n\x02KW\x10\n\x12\x07\n\x03KWH\x10\x0b\x12\x07\n\x03\x41MP\x10\x0c\x12\x0b\n\x07NO_UNIT\x10\r\x12\x08\n\x04VOLT\x10\x0e\x12\x07\n\x03KPA\x10\x0f\x12\x07\n\x03\x44\x41Y\x10\x11\x12\x07\n\x03Wm2\x10\x12\x12\x08\n\x04KMPL\x10\x13\x12\x07\n\x03LUX\x10\x14\x12\t\n\x05HOURS\x10\x15\x12\x0b\n\x07MINUTES\x10\x16\x12\x0b\n\x07SECONDS\x10\x17\x12\n\n\x06METERS\x10\x18\x12\x0f\n\x0b\x43\x45NTIMETERS\x10\x19\x12\x0b\n\x07\x44\x45GREES\x10\x1a\x12\x0e\n\nKM_PER_KWH\x10\x1b\x12\x0e\n\nKWH_PER_KM\x10\x1c\x12\x06\n\x02ms\x10\x1d\x42\x17\n\x13org.covesa.userviceP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'units_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023org.covesa.userviceP\001'
  _UNITS._serialized_start=16
  _UNITS._serialized_end=356
# @@protoc_insertion_point(module_scope)
