# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle/body/horn/v1/horn_topics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protofiles.uservices_options_pb2 as uservices__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&vehicle/body/horn/v1/horn_topics.proto\x12\x14vehicle.body.horn.v1\x1a\x17uservices_options.proto\"\x83\x03\n\nHornStatus\x12\x11\n\tis_active\x18\x01 \x01(\x08\x12,\n\x04mode\x18\x02 \x01(\x0e\x32\x1e.vehicle.body.horn.v1.HornMode\x12\x17\n\x0fis_fault_active\x18\x03 \x01(\x08\x12\x39\n\x10\x63urrent_sequence\x18\x04 \x01(\x05\x42\x1a\xc8\x8c\x19\x01\xe9\x8c\x19\x00\x00\x00\x00\x00\x00\x00\x00\xe1\x8c\x19\x00\x00\x00\x00\x00\x00\x1c@H\x00\x88\x01\x01\x12.\n\x10remaining_cycles\x18\x05 \x01(\x05\x42\x0f\xc8\x8c\x19\x01\xe9\x8c\x19\x00\x00\x00\x00\x00\x00\x00\x00H\x01\x88\x01\x01\x12\x38\n\x0ftotal_sequences\x18\x06 \x01(\x05\x42\x1a\xc8\x8c\x19\x01\xe9\x8c\x19\x00\x00\x00\x00\x00\x00\x00\x00\xe1\x8c\x19\x00\x00\x00\x00\x00\x00\x1c@H\x02\x88\x01\x01\x12!\n\x08priority\x18\x07 \x01(\x05\x42\x0f\xc8\x8c\x19\x01\xe1\x8c\x19\x00\x00\x00\x00\x00\xe0o@\"\x15\n\tResources\x12\x08\n\x04horn\x10\x00\x42\x13\n\x11_current_sequenceB\x13\n\x11_remaining_cyclesB\x12\n\x10_total_sequences\"D\n\x0cHornSequence\x12\x34\n\x0bhorn_cycles\x18\x01 \x03(\x0b\x32\x1f.vehicle.body.horn.v1.HornCycle\"X\n\tHornCycle\x12$\n\x07on_time\x18\x01 \x01(\x05\x42\x13\xd8\x8c\x19\x1d\xe9\x8c\x19\x00\x00\x00\x00\x00\x00>@\xd0\x8c\x19\x01\x12%\n\x08off_time\x18\x02 \x01(\x05\x42\x13\xd8\x8c\x19\x1d\xe9\x8c\x19\x00\x00\x00\x00\x00\x00>@\xd0\x8c\x19\x01*S\n\x08HornMode\x12\x12\n\x0eHM_UNSPECIFIED\x10\x00\x12\x0e\n\nHM_UNKNOWN\x10\x01\x12\x10\n\x0cHM_SEQUENCED\x10\x02\x12\x11\n\rHM_CONTINUOUS\x10\x03\x42,\n(org.covesa.uservice.vehicle.body.horn.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle.body.horn.v1.horn_topics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n(org.covesa.uservice.vehicle.body.horn.v1P\001'
  _HORNSTATUS.fields_by_name['current_sequence']._options = None
  _HORNSTATUS.fields_by_name['current_sequence']._serialized_options = b'\310\214\031\001\351\214\031\000\000\000\000\000\000\000\000\341\214\031\000\000\000\000\000\000\034@'
  _HORNSTATUS.fields_by_name['remaining_cycles']._options = None
  _HORNSTATUS.fields_by_name['remaining_cycles']._serialized_options = b'\310\214\031\001\351\214\031\000\000\000\000\000\000\000\000'
  _HORNSTATUS.fields_by_name['total_sequences']._options = None
  _HORNSTATUS.fields_by_name['total_sequences']._serialized_options = b'\310\214\031\001\351\214\031\000\000\000\000\000\000\000\000\341\214\031\000\000\000\000\000\000\034@'
  _HORNSTATUS.fields_by_name['priority']._options = None
  _HORNSTATUS.fields_by_name['priority']._serialized_options = b'\310\214\031\001\341\214\031\000\000\000\000\000\340o@'
  _HORNCYCLE.fields_by_name['on_time']._options = None
  _HORNCYCLE.fields_by_name['on_time']._serialized_options = b'\330\214\031\035\351\214\031\000\000\000\000\000\000>@\320\214\031\001'
  _HORNCYCLE.fields_by_name['off_time']._options = None
  _HORNCYCLE.fields_by_name['off_time']._serialized_options = b'\330\214\031\035\351\214\031\000\000\000\000\000\000>@\320\214\031\001'
  _HORNMODE._serialized_start=639
  _HORNMODE._serialized_end=722
  _HORNSTATUS._serialized_start=90
  _HORNSTATUS._serialized_end=477
  _HORNSTATUS_RESOURCES._serialized_start=394
  _HORNSTATUS_RESOURCES._serialized_end=415
  _HORNSEQUENCE._serialized_start=479
  _HORNSEQUENCE._serialized_end=547
  _HORNCYCLE._serialized_start=549
  _HORNCYCLE._serialized_end=637
# @@protoc_insertion_point(module_scope)
