# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/hello_world/v1/hello_world_topics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.type import timeofday_pb2 as google_dot_type_dot_timeofday__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/example/hello_world/v1/hello_world_topics.proto\x12\x16\x65xample.hello_world.v1\x1a\x1bgoogle/type/timeofday.proto\"Z\n\x05Timer\x12$\n\x04time\x18\x01 \x01(\x0b\x32\x16.google.type.TimeOfDay\"+\n\tResources\x12\x0e\n\none_second\x10\x00\x12\x0e\n\none_minute\x10\x01\x42.\n*org.covesa.uservice.example.hello_world.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.hello_world.v1.hello_world_topics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*org.covesa.uservice.example.hello_world.v1P\001'
  _TIMER._serialized_start=104
  _TIMER._serialized_end=194
  _TIMER_RESOURCES._serialized_start=151
  _TIMER_RESOURCES._serialized_end=194
# @@protoc_insertion_point(module_scope)
