# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle/propulsion/transmission/v1/transmission_topics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
import simulator.core.protofiles.uservices_options_pb2 as uservices__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<vehicle/propulsion/transmission/v1/transmission_topics.proto\x12\"vehicle.propulsion.transmission.v1\x1a google/protobuf/descriptor.proto\x1a\x17uservices_options.proto\"\xf3\x01\n\x10VehicleGearState\x12U\n\rselected_gear\x18\x01 \x01(\x0e\x32\x39.vehicle.propulsion.transmission.v1.VehicleGearState.GearH\x00\x88\x01\x01\"_\n\x04Gear\x12\x11\n\rS_UNSPECIFIED\x10\x00\x12\r\n\tS_UNKNOWN\x10\x01\x12\n\n\x06S_PARK\x10\x02\x12\r\n\tS_REVERSE\x10\x03\x12\r\n\tS_NEUTRAL\x10\x04\x12\x0b\n\x07S_DRIVE\x10\x05\"\x15\n\tResources\x12\x08\n\x04gear\x10\x00\x42\x10\n\x0e_selected_gear\"\x80\x01\n\x07Gearbox\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x11\x66luid_temperature\x18\x02 \x01(\x02\x42\x08\xd8\x8c\x19\x03\xc8\x8c\x19\x01H\x00\x88\x01\x01\"\'\n\tResources\x12\x0b\n\x07primary\x10\x00\x12\r\n\tsecondary\x10\x01\x42\x14\n\x12_fluid_temperatureB2\n.org.covesa.uservice.propulsion.transmission.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle.propulsion.transmission.v1.transmission_topics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n.org.covesa.uservice.propulsion.transmission.v1P\001'
  _GEARBOX.fields_by_name['fluid_temperature']._options = None
  _GEARBOX.fields_by_name['fluid_temperature']._serialized_options = b'\330\214\031\003\310\214\031\001'
  _VEHICLEGEARSTATE._serialized_start=160
  _VEHICLEGEARSTATE._serialized_end=403
  _VEHICLEGEARSTATE_GEAR._serialized_start=267
  _VEHICLEGEARSTATE_GEAR._serialized_end=362
  _VEHICLEGEARSTATE_RESOURCES._serialized_start=364
  _VEHICLEGEARSTATE_RESOURCES._serialized_end=385
  _GEARBOX._serialized_start=406
  _GEARBOX._serialized_end=534
  _GEARBOX_RESOURCES._serialized_start=473
  _GEARBOX_RESOURCES._serialized_end=512
# @@protoc_insertion_point(module_scope)
