# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle/propulsion/transmission/v1/transmission_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import uprotocol_options_pb2 as uprotocol__options__pb2
from vehicle.propulsion.transmission.v1 import transmission_topics_pb2 as vehicle_dot_propulsion_dot_transmission_dot_v1_dot_transmission__topics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=vehicle/propulsion/transmission/v1/transmission_service.proto\x12\"vehicle.propulsion.transmission.v1\x1a\x17uprotocol_options.proto\x1a<vehicle/propulsion/transmission/v1/transmission_topics.proto\"}\n\x17VehicleGearStateOptions\x12\\\n\rresource_name\x18\x01 \x01(\x0e\x32>.vehicle.propulsion.transmission.v1.VehicleGearState.ResourcesB\x05\x82\xce\x18\x01*:\x04\xe0\xc7\x18\x00\"s\n\x0eGearboxOptions\x12[\n\rresource_name\x18\x01 \x01(\x0e\x32\x35.vehicle.propulsion.transmission.v1.Gearbox.ResourcesB\r\x82\xce\x18\tgearbox.*:\x04\xe0\xc7\x18\n27\n\x0cTransmission\x1a\'\xa2\xbb\x18\x17propulsion.transmission\xa8\xbb\x18\x01\xb0\xbb\x18\x00\xb8\xbb\x18\x12\x42\x32\n.org.covesa.uservice.propulsion.transmission.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle.propulsion.transmission.v1.transmission_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n.org.covesa.uservice.propulsion.transmission.v1P\001'
  _VEHICLEGEARSTATEOPTIONS.fields_by_name['resource_name']._options = None
  _VEHICLEGEARSTATEOPTIONS.fields_by_name['resource_name']._serialized_options = b'\202\316\030\001*'
  _VEHICLEGEARSTATEOPTIONS._options = None
  _VEHICLEGEARSTATEOPTIONS._serialized_options = b'\340\307\030\000'
  _GEARBOXOPTIONS.fields_by_name['resource_name']._options = None
  _GEARBOXOPTIONS.fields_by_name['resource_name']._serialized_options = b'\202\316\030\tgearbox.*'
  _GEARBOXOPTIONS._options = None
  _GEARBOXOPTIONS._serialized_options = b'\340\307\030\n'
  _TRANSMISSION._options = None
  _TRANSMISSION._serialized_options = b'\242\273\030\027propulsion.transmission\250\273\030\001\260\273\030\000\270\273\030\022'
  _VEHICLEGEARSTATEOPTIONS._serialized_start=188
  _VEHICLEGEARSTATEOPTIONS._serialized_end=313
  _GEARBOXOPTIONS._serialized_start=315
  _GEARBOXOPTIONS._serialized_end=430
  _TRANSMISSION._serialized_start=432
  _TRANSMISSION._serialized_end=487
# @@protoc_insertion_point(module_scope)
