# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle/v1/vehicle_topics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import simulator.core.protofiles.uservices_options_pb2 as uservices__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fvehicle/v1/vehicle_topics.proto\x12\nvehicle.v1\x1a\x17uservices_options.proto\"Y\n\x10TraveledDistance\x12\x12\n\nis_invalid\x18\x01 \x01(\x08\x12\x17\n\x05value\x18\x02 \x01(\x02\x42\x08\xd8\x8c\x19\t\xc8\x8c\x19\x01\"\x18\n\tResources\x12\x0b\n\x07vehicle\x10\x00\"g\n\tTripMeter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nis_invalid\x18\x02 \x01(\x08\x12\x13\n\x05value\x18\x03 \x01(\x02\x42\x04\xd8\x8c\x19\t\"#\n\tResources\x12\n\n\x06trip_1\x10\x00\x12\n\n\x06trip_2\x10\x01\"\x90\x01\n\x0cVehicleSpeed\x12\x1c\n\x05speed\x18\x01 \x01(\x02\x42\x08\xd8\x8c\x19\x01\xc8\x8c\x19\x01H\x00\x88\x01\x01\x12\x19\n\x0bspeed_limit\x18\x02 \x01(\x02\x42\x04\xd8\x8c\x19\x01\x12#\n\x15is_speed_limit_active\x18\x03 \x01(\x08\x42\x04\xc8\x8c\x19\x01\"\x18\n\tResources\x12\x0b\n\x07vehicle\x10\x00\x42\x08\n\x06_speed\"C\n\x0e\x43ollisionAlert\x12\x17\n\tis_active\x18\x01 \x01(\x08\x42\x04\xc8\x8c\x19\x01\"\x18\n\tResources\x12\x0b\n\x07vehicle\x10\x00\"?\n\nTheftAlert\x12\x17\n\tis_active\x18\x01 \x01(\x08\x42\x04\xc8\x8c\x19\x01\"\x18\n\tResources\x12\x0b\n\x07vehicle\x10\x00\"e\n\x0cVehicleUsage\x12\x11\n\tis_active\x18\x01 \x01(\x08\x12!\n\x19is_setting_change_allowed\x18\x02 \x01(\x08\"\x1f\n\tResources\x12\x12\n\x0etransport_mode\x10\x00\x42\"\n\x1eorg.covesa.uservice.vehicle.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle.v1.vehicle_topics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036org.covesa.uservice.vehicle.v1P\001'
  _TRAVELEDDISTANCE.fields_by_name['value']._options = None
  _TRAVELEDDISTANCE.fields_by_name['value']._serialized_options = b'\330\214\031\t\310\214\031\001'
  _TRIPMETER.fields_by_name['value']._options = None
  _TRIPMETER.fields_by_name['value']._serialized_options = b'\330\214\031\t'
  _VEHICLESPEED.fields_by_name['speed']._options = None
  _VEHICLESPEED.fields_by_name['speed']._serialized_options = b'\330\214\031\001\310\214\031\001'
  _VEHICLESPEED.fields_by_name['speed_limit']._options = None
  _VEHICLESPEED.fields_by_name['speed_limit']._serialized_options = b'\330\214\031\001'
  _VEHICLESPEED.fields_by_name['is_speed_limit_active']._options = None
  _VEHICLESPEED.fields_by_name['is_speed_limit_active']._serialized_options = b'\310\214\031\001'
  _COLLISIONALERT.fields_by_name['is_active']._options = None
  _COLLISIONALERT.fields_by_name['is_active']._serialized_options = b'\310\214\031\001'
  _THEFTALERT.fields_by_name['is_active']._options = None
  _THEFTALERT.fields_by_name['is_active']._serialized_options = b'\310\214\031\001'
  _TRAVELEDDISTANCE._serialized_start=72
  _TRAVELEDDISTANCE._serialized_end=161
  _TRAVELEDDISTANCE_RESOURCES._serialized_start=137
  _TRAVELEDDISTANCE_RESOURCES._serialized_end=161
  _TRIPMETER._serialized_start=163
  _TRIPMETER._serialized_end=266
  _TRIPMETER_RESOURCES._serialized_start=231
  _TRIPMETER_RESOURCES._serialized_end=266
  _VEHICLESPEED._serialized_start=269
  _VEHICLESPEED._serialized_end=413
  _VEHICLESPEED_RESOURCES._serialized_start=137
  _VEHICLESPEED_RESOURCES._serialized_end=161
  _COLLISIONALERT._serialized_start=415
  _COLLISIONALERT._serialized_end=482
  _COLLISIONALERT_RESOURCES._serialized_start=137
  _COLLISIONALERT_RESOURCES._serialized_end=161
  _THEFTALERT._serialized_start=484
  _THEFTALERT._serialized_end=547
  _THEFTALERT_RESOURCES._serialized_start=137
  _THEFTALERT_RESOURCES._serialized_end=161
  _VEHICLEUSAGE._serialized_start=549
  _VEHICLEUSAGE._serialized_end=650
  _VEHICLEUSAGE_RESOURCES._serialized_start=619
  _VEHICLEUSAGE_RESOURCES._serialized_end=650
# @@protoc_insertion_point(module_scope)
