# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle/propulsion/engine/v1/engine_topics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protofiles.common import health_state_pb2 as common_dot_health__state__pb2
import protofiles.uservices_options_pb2 as uservices__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0vehicle/propulsion/engine/v1/engine_topics.proto\x12\x1cvehicle.propulsion.engine.v1\x1a\x19\x63ommon/health_state.proto\x1a\x17uservices_options.proto\"M\n\tAirFilter\x12#\n\x06health\x18\x01 \x01(\x0b\x32\x13.common.HealthState\"\x1b\n\tResources\x12\x0e\n\nair_filter\x10\x00\"\x8c\x02\n\x03Oil\x12\x18\n\nis_invalid\x18\x01 \x01(\x08\x42\x04\xc8\x8c\x19\x01\x12\x1b\n\x08pressure\x18\x02 \x01(\x02\x42\x04\xc8\x8c\x19\x01H\x00\x88\x01\x01\x12\x30\n\x1dis_pressure_low_indication_on\x18\x03 \x01(\x08\x42\x04\xc8\x8c\x19\x01H\x01\x88\x01\x01\x12#\n\x06health\x18\x04 \x01(\x0b\x32\x13.common.HealthState\x12\"\n\x0btemperature\x18\x05 \x01(\x02\x42\x08\xc8\x8c\x19\x01\xd8\x8c\x19\x03H\x02\x88\x01\x01\"\x14\n\tResources\x12\x07\n\x03oil\x10\x00\x42\x0b\n\t_pressureB \n\x1e_is_pressure_low_indication_onB\x0e\n\x0c_temperature\"^\n\x07\x43oolant\x12\x18\n\nis_invalid\x18\x01 \x01(\x08\x42\x04\xc8\x8c\x19\x01\x12\x1f\n\x11inlet_temperature\x18\x02 \x01(\x02\x42\x04\xc8\x8c\x19\x01\"\x18\n\tResources\x12\x0b\n\x07\x63oolant\x10\x00\"\x83\x01\n\x0b\x45ngineState\x12\x18\n\nis_running\x18\x01 \x01(\x08\x42\x04\xc8\x8c\x19\x01\x12\x1e\n\x10running_duration\x18\x02 \x01(\x05\x42\x04\xc8\x8c\x19\x01\x12\x1b\n\ridle_duration\x18\x03 \x01(\x05\x42\x04\xc8\x8c\x19\x01\"\x1d\n\tResources\x12\x10\n\x0c\x65ngine_state\x10\x00\x42\x34\n0org.covesa.uservice.vehicle.propulsion.engine.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle.propulsion.engine.v1.engine_topics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n0org.covesa.uservice.vehicle.propulsion.engine.v1P\001'
  _OIL.fields_by_name['is_invalid']._options = None
  _OIL.fields_by_name['is_invalid']._serialized_options = b'\310\214\031\001'
  _OIL.fields_by_name['pressure']._options = None
  _OIL.fields_by_name['pressure']._serialized_options = b'\310\214\031\001'
  _OIL.fields_by_name['is_pressure_low_indication_on']._options = None
  _OIL.fields_by_name['is_pressure_low_indication_on']._serialized_options = b'\310\214\031\001'
  _OIL.fields_by_name['temperature']._options = None
  _OIL.fields_by_name['temperature']._serialized_options = b'\310\214\031\001\330\214\031\003'
  _COOLANT.fields_by_name['is_invalid']._options = None
  _COOLANT.fields_by_name['is_invalid']._serialized_options = b'\310\214\031\001'
  _COOLANT.fields_by_name['inlet_temperature']._options = None
  _COOLANT.fields_by_name['inlet_temperature']._serialized_options = b'\310\214\031\001'
  _ENGINESTATE.fields_by_name['is_running']._options = None
  _ENGINESTATE.fields_by_name['is_running']._serialized_options = b'\310\214\031\001'
  _ENGINESTATE.fields_by_name['running_duration']._options = None
  _ENGINESTATE.fields_by_name['running_duration']._serialized_options = b'\310\214\031\001'
  _ENGINESTATE.fields_by_name['idle_duration']._options = None
  _ENGINESTATE.fields_by_name['idle_duration']._serialized_options = b'\310\214\031\001'
  _AIRFILTER._serialized_start=134
  _AIRFILTER._serialized_end=211
  _AIRFILTER_RESOURCES._serialized_start=184
  _AIRFILTER_RESOURCES._serialized_end=211
  _OIL._serialized_start=214
  _OIL._serialized_end=482
  _OIL_RESOURCES._serialized_start=399
  _OIL_RESOURCES._serialized_end=419
  _COOLANT._serialized_start=484
  _COOLANT._serialized_end=578
  _COOLANT_RESOURCES._serialized_start=554
  _COOLANT_RESOURCES._serialized_end=578
  _ENGINESTATE._serialized_start=581
  _ENGINESTATE._serialized_end=712
  _ENGINESTATE_RESOURCES._serialized_start=683
  _ENGINESTATE_RESOURCES._serialized_end=712
# @@protoc_insertion_point(module_scope)
