# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle/body/mirrors/v1/mirrors_topics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,vehicle/body/mirrors/v1/mirrors_topics.proto\x12\x17vehicle.body.mirrors.v1\"C\n\x10HeatedSideMirror\x12\x12\n\nis_heat_on\x18\x01 \x01(\x08\"\x1b\n\x08Resource\x12\x0f\n\x0bside_mirror\x10\x00\"u\n\x1aSideMirrorMovementSettings\x12\x1c\n\x14is_auto_tilt_enabled\x18\x01 \x01(\x08\x12\x1c\n\x14is_auto_fold_enabled\x18\x02 \x01(\x08\"\x1b\n\x08Resource\x12\x0f\n\x0bside_mirror\x10\x00\"P\n\x18HeatedSideMirrorSettings\x12\x17\n\x0fis_auto_heat_on\x18\x01 \x01(\x08\"\x1b\n\x08Resource\x12\x0f\n\x0bside_mirror\x10\x00\"w\n\x12\x45xteriorSideMirror\x12@\n\x02id\x18\x01 \x01(\x0e\x32\x34.vehicle.body.mirrors.v1.ExteriorSideMirror.Resource\"\x1f\n\x08Resource\x12\x08\n\x04left\x10\x00\x12\t\n\x05right\x10\x01\x42/\n+org.covesa.uservice.vehicle.body.mirrors.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle.body.mirrors.v1.mirrors_topics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+org.covesa.uservice.vehicle.body.mirrors.v1P\001'
  _HEATEDSIDEMIRROR._serialized_start=73
  _HEATEDSIDEMIRROR._serialized_end=140
  _HEATEDSIDEMIRROR_RESOURCE._serialized_start=113
  _HEATEDSIDEMIRROR_RESOURCE._serialized_end=140
  _SIDEMIRRORMOVEMENTSETTINGS._serialized_start=142
  _SIDEMIRRORMOVEMENTSETTINGS._serialized_end=259
  _SIDEMIRRORMOVEMENTSETTINGS_RESOURCE._serialized_start=113
  _SIDEMIRRORMOVEMENTSETTINGS_RESOURCE._serialized_end=140
  _HEATEDSIDEMIRRORSETTINGS._serialized_start=261
  _HEATEDSIDEMIRRORSETTINGS._serialized_end=341
  _HEATEDSIDEMIRRORSETTINGS_RESOURCE._serialized_start=113
  _HEATEDSIDEMIRRORSETTINGS_RESOURCE._serialized_end=140
  _EXTERIORSIDEMIRROR._serialized_start=343
  _EXTERIORSIDEMIRROR._serialized_end=462
  _EXTERIORSIDEMIRROR_RESOURCE._serialized_start=431
  _EXTERIORSIDEMIRROR_RESOURCE._serialized_end=462
# @@protoc_insertion_point(module_scope)
