# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicle/exterior/v1/exterior_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import uprotocol_options_pb2 as uprotocol__options__pb2
from vehicle.exterior.v1 import exterior_topics_pb2 as vehicle_dot_exterior_dot_v1_dot_exterior__topics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*vehicle/exterior/v1/exterior_service.proto\x12\x13vehicle.exterior.v1\x1a\x17uprotocol_options.proto\x1a)vehicle/exterior/v1/exterior_topics.proto\"n\n\x17SolarInformationOptions\x12M\n\rresource_name\x18\x01 \x01(\x0e\x32/.vehicle.exterior.v1.SolarInformation.ResourcesB\x05\x82\xce\x18\x01*:\x04\xe0\xc7\x18\x00\"d\n\x12TemperatureOptions\x12H\n\rresource_name\x18\x01 \x01(\x0e\x32*.vehicle.exterior.v1.Temperature.ResourcesB\x05\x82\xce\x18\x01*:\x04\xe0\xc7\x18\n\"f\n\x13\x41mbientLightOptions\x12I\n\rresource_name\x18\x01 \x01(\x0e\x32+.vehicle.exterior.v1.AmbientLight.ResourcesB\x05\x82\xce\x18\x01*:\x04\xe0\xc7\x18\x14\x32\x33\n\x0fVehicleExterior\x1a \xa2\xbb\x18\x10vehicle.exterior\xa8\xbb\x18\x01\xb0\xbb\x18\x00\xb8\xbb\x18\x10\x42+\n\'org.covesa.uservice.vehicle.exterior.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle.exterior.v1.exterior_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'org.covesa.uservice.vehicle.exterior.v1P\001'
  _SOLARINFORMATIONOPTIONS.fields_by_name['resource_name']._options = None
  _SOLARINFORMATIONOPTIONS.fields_by_name['resource_name']._serialized_options = b'\202\316\030\001*'
  _SOLARINFORMATIONOPTIONS._options = None
  _SOLARINFORMATIONOPTIONS._serialized_options = b'\340\307\030\000'
  _TEMPERATUREOPTIONS.fields_by_name['resource_name']._options = None
  _TEMPERATUREOPTIONS.fields_by_name['resource_name']._serialized_options = b'\202\316\030\001*'
  _TEMPERATUREOPTIONS._options = None
  _TEMPERATUREOPTIONS._serialized_options = b'\340\307\030\n'
  _AMBIENTLIGHTOPTIONS.fields_by_name['resource_name']._options = None
  _AMBIENTLIGHTOPTIONS.fields_by_name['resource_name']._serialized_options = b'\202\316\030\001*'
  _AMBIENTLIGHTOPTIONS._options = None
  _AMBIENTLIGHTOPTIONS._serialized_options = b'\340\307\030\024'
  _VEHICLEEXTERIOR._options = None
  _VEHICLEEXTERIOR._serialized_options = b'\242\273\030\020vehicle.exterior\250\273\030\001\260\273\030\000\270\273\030\020'
  _SOLARINFORMATIONOPTIONS._serialized_start=135
  _SOLARINFORMATIONOPTIONS._serialized_end=245
  _TEMPERATUREOPTIONS._serialized_start=247
  _TEMPERATUREOPTIONS._serialized_end=347
  _AMBIENTLIGHTOPTIONS._serialized_start=349
  _AMBIENTLIGHTOPTIONS._serialized_end=451
  _VEHICLEEXTERIOR._serialized_start=453
  _VEHICLEEXTERIOR._serialized_end=504
# @@protoc_insertion_point(module_scope)
