# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/hello_world/v1/hello_world_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from example.hello_world.v1 import hello_world_topics_pb2 as example_dot_hello__world_dot_v1_dot_hello__world__topics__pb2
import uprotocol_options_pb2 as uprotocol__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0example/hello_world/v1/hello_world_service.proto\x12\x16\x65xample.hello_world.v1\x1a/example/hello_world/v1/hello_world_topics.proto\x1a\x17uprotocol_options.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"[\n\x0cTimerOptions\x12\x45\n\rresource_name\x18\x01 \x01(\x0e\x32\'.example.hello_world.v1.Timer.ResourcesB\x05\x82\xce\x18\x01*:\x04\xe0\xc7\x18\x01\x32\x91\x01\n\nHelloWorld\x12]\n\x08SayHello\x12$.example.hello_world.v1.HelloRequest\x1a%.example.hello_world.v1.HelloResponse\"\x04\xc0\xc1\x18\x01\x1a$\xa2\xbb\x18\x13\x65xample.hello_world\xa8\xbb\x18\x01\xb0\xbb\x18\x00\xb8\xbb\x18\xe7\x07\x42.\n*org.covesa.uservice.example.hello_world.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.hello_world.v1.hello_world_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*org.covesa.uservice.example.hello_world.v1P\001'
  _TIMEROPTIONS.fields_by_name['resource_name']._options = None
  _TIMEROPTIONS.fields_by_name['resource_name']._serialized_options = b'\202\316\030\001*'
  _TIMEROPTIONS._options = None
  _TIMEROPTIONS._serialized_options = b'\340\307\030\001'
  _HELLOWORLD._options = None
  _HELLOWORLD._serialized_options = b'\242\273\030\023example.hello_world\250\273\030\001\260\273\030\000\270\273\030\347\007'
  _HELLOWORLD.methods_by_name['SayHello']._options = None
  _HELLOWORLD.methods_by_name['SayHello']._serialized_options = b'\300\301\030\001'
  _HELLOREQUEST._serialized_start=150
  _HELLOREQUEST._serialized_end=178
  _HELLORESPONSE._serialized_start=180
  _HELLORESPONSE._serialized_end=212
  _TIMEROPTIONS._serialized_start=214
  _TIMEROPTIONS._serialized_end=305
  _HELLOWORLD._serialized_start=308
  _HELLOWORLD._serialized_end=453
# @@protoc_insertion_point(module_scope)
